sudo: required

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install --prefer-dist --no-interaction

notifications:
  email:
    recipients:
      - olegabrosimovnsk@gmail.com
    on_success: always
    on_failure: always

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 0eb07ff9-4fbc-4011-8747-e0d098e1bf01
